### PR TITLE
Replace `jsnext:main` with `module`

### PR DESCRIPTION
**Pull request by jfsiii**
See discussion in https://github.com/d3/d3-selection-multi/pull/12

### CODE REVIEW

**Comment by ghost** [comment]
It's all?

**Comment by jfsiii** [comment]
@acterhd Yeah, that's all that's required for tools to find the ES6+ source.

Mind bumping the version (patch?) and deploying to npm?

**Comment by ghost** [comment]
I cannot successfully npm publish because my system are Windows, and have no "zip" executable. 
I bumped to 0.0.9, but not well done.

**Comment by mbostock** [comment]
@acterhd You can remove the postpublish hook from the package.json, if you like. It looks like you’ve published [d3-hcg@0.0.9](https://www.npmjs.com/package/d3-hcg) to npm successfully. I do recommend using `npm version patch` (or `npm version minor`, etc.) to create a commit and a git tag, and then running `git push && git push --tags` to push that to GitHub. I also like to create a zipball of the built files and attach it to the GitHub release, but whether you do that manually or automatically is up to you.

**Comment by curran** [comment]
@acterhd In case it might help, here's what I did to remove some problematic bits from the postpublish hook in d3-tile https://github.com/d3/d3-tile/pull/29/files

**Pull request merged**
